
services:
  claude:
    image: claude-code-env
    working_dir: /app
    user: "${LOCAL_UID:-1000}:${LOCAL_GID:-1000}"
    environment:
      # Force all config/cache/data to live under /settings (persisted)
      - HOME=/settings
      - XDG_CONFIG_HOME=/settings/config
      - XDG_CACHE_HOME=/settings/cache
      - XDG_DATA_HOME=/settings/data
    volumes:
      - ${PROJECT_ROOT}:/app   # set by the script below
      - ${CLAUDE_SETTINGS_DIR}:/settings
    stdin_open: true           # same as -i
    tty: true                  # same as -t
    network_mode: "bridge"     # explicit: outbound internet via NAT, no inbound ports
